const express = require('express')
const route = express.Router()
const {auth,IsOrganizer,IsAdmin} = require('../middlewares/verification')
const {VerifyShow} = require('../controllers/Administrator/ShowVerify')
const {CreateShow,UpdateShowtitle,PosterLike,BannerDisliked,AllotedToTheatres,uploadtheshow} = require('../controllers/Orgainezer/CreateTheatreShow')
route.post('/CreateShow',auth,IsOrganizer,CreateShow)
route.put('/UpdateTitle/:id',auth,IsOrganizer,UpdateShowtitle)
route.put('/TheatresAllotment',auth,IsOrganizer,AllotedToTheatres)
route.put('/likePoster',auth,PosterLike)
route.put('/DislikePoster',auth,BannerDisliked)
route.put('/upload',auth,IsOrganizer,uploadtheshow)
module.exports = route