const express = require('express')
const route = express.Router()
const {auth} = require('../middlewares/verification')
const {Createuser,CreateOtp,CurrentLoginUser} = require('../controllers/user/Createuser')
const {login} = require('../controllers/user/auth')
const {SendPersonalMessage,SendProfessionalMessage} = require('../controllers/common/SendMessage')
const {Comment} = require('../controllers/common/Comment')
route.post('/CreateUser',Createuser)
route.post('/Login',login)
route.post('/SendOtp',CreateOtp)
route.get('/User',auth,CurrentLoginUser)
route.post('/Messagepersonal',auth,SendPersonalMessage)
route.post('/MessageProfessional',auth,SendProfessionalMessage)
route.post('/Comment',auth,Comment)
module.exports = route