const mongoose = require('mongoose')
const userSchema =  new mongoose.Schema({
    userName:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
        minlength:8
    },
    confirmpass:{
        type:String,
        required:true,
    },
    token:{
        type:String
    },
    id:{
        type:String,
    },
    email:{
        type:String,
        required:true,
        unique: true,
        lowercase:true,
        match: [/^\S+@\S+\.\S+$/, "Invalid email format"],
    },
    usertype:{
        type:String,
        required:true,
        enum:["Viewer","Organizer","Administrator"],
        default:"Viewer"
    },
    verified:{
        type:Boolean,
        default:false
    },
    number:{
        type:String,
        required:true,
        match: [/^\d{10}$/, "Invalid phone number"],
    },
    image:{
        type:String,
        required:true
    },
    resetPasswordExpires:{
        type:Date,
        index:{expires:'120'}
    },
    theatresCreated:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Theatrees'
    },
    ticketCreated:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Ticket"
    },
    languagesCreated:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Languages"
    },
    showsCreated:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"show"
    },
    Casttaken:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Cast"
    },
    currentlocation:{
        latitude:{
            type:String,
        },
        longitude:{
            type:String,
        },
        name:{
            type:String,
        }
    },
    createdAt:{
        type:String,
        required:true
    },
    lastlogin:[{
        type:String,
        required:true
    }],
    Bannerliked:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Show'
    }],
    Bannerhated:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Show'
    }]
},{timestamps:true})
module.exports = mongoose.model('User',userSchema)